# Generated by Django 4.1.13 on 2024-08-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(choices=[(1, 'Uploaded'), (2, 'Processing'), (3, 'Embedding Saved'), (4, 'Completed'), (5, 'Error')], default=1),
        ),
    ]
